#!/usr/bin/env python3
"""Generate README.md files under packs/ from pack metadata.

Run this after validate-packs.py on the main branch. It produces:

  - packs/<game-slug>/README.md          — game-level summary with pair table
  - packs/<game-slug>/<pair>/README.md   — pair-specific summary

Contributors should NOT hand-edit these files. They are regenerated from the
pack content on every push to main. If you want to add subjective notes
(known gaps, special capture tips), add them to the pack's `profile.context.prompt_hint`
field before export — the generator renders that into the README.

Usage:
  python scripts/generate-readmes.py            # regenerate all
  python scripts/generate-readmes.py --check    # exit 1 if any README would change (CI sanity)
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKS_DIR = ROOT / "packs"

# Generated file marker — lets readers know not to hand-edit
HEADER_MARKER = "<!-- generated by scripts/generate-readmes.py from pack metadata — edit the pack, not this file -->"

LANG_NAMES = {
    "en": "English",
    "ja": "Japanese",
    "zh": "Chinese",
    "ko": "Korean",
    "de": "German",
    "fr": "French",
    "es": "Spanish",
    "pt": "Portuguese",
    "ru": "Russian",
    "it": "Italian",
    "pl": "Polish",
    "vi": "Vietnamese",
}

CATEGORY_LABELS = {
    "character": "Characters",
    "location": "Locations",
    "item": "Items / Cards",
    "skill": "Skills",
    "game_term": "Game terms",
    "": "Uncategorized",
}


def lang_name(code: str) -> str:
    return LANG_NAMES.get(code, code.upper())


def load_pack(pack_file: Path) -> dict:
    return json.loads(pack_file.read_text(encoding="utf-8"))


def glossary_dict(pack: dict) -> dict:
    ctx = pack.get("profile", {}).get("context", {})
    g = ctx.get("glossary", {})
    # v1 fallback: top-level array
    if not g and isinstance(pack.get("glossary"), list):
        return {
            e["source"]: {"target": e.get("target", ""), "category": e.get("category", "")}
            for e in pack["glossary"]
            if isinstance(e, dict) and "source" in e
        }
    return g or {}


def category_breakdown(glossary: dict) -> dict:
    counts: dict = {}
    for entry in glossary.values():
        cat = (entry.get("category") or "") if isinstance(entry, dict) else ""
        counts[cat] = counts.get(cat, 0) + 1
    return counts


def render_pair_readme(pack_file: Path, pack: dict, game_slug: str, pair_slug: str) -> str:
    game = pack.get("game", {})
    title = game.get("title") or game_slug.replace("-", " ").title()
    contributor = pack.get("contributor") or pack.get("summary", {}).get("contributor") or "anonymous"
    fv = pack.get("format_version", 1)

    src = pair_slug.split("-")[0]
    tgt = pair_slug.split("-")[1] if "-" in pair_slug else ""

    gloss = glossary_dict(pack)
    cats = category_breakdown(gloss)
    cat_rows = "".join(
        f"| {CATEGORY_LABELS.get(cat, cat or 'Uncategorized')} | {count} |\n"
        for cat, count in sorted(cats.items(), key=lambda x: (-x[1], x[0]))
    )

    profile = pack.get("profile", {})
    ctx = profile.get("context", {})
    style = ctx.get("style") or "(not specified)"
    world = ctx.get("world") or "(not specified)"
    prompt_hint = ctx.get("prompt_hint") or ""

    cap = profile.get("capture_settings", {})
    cap_mode = cap.get("mode") or "(not specified)"
    cap_summary = f"{cap_mode}"
    if cap_mode == "cursor":
        cap_summary += (
            f" (cursor window {cap.get('cursor_w', '?')}×{cap.get('cursor_h', '?')}, "
            f"offset x={cap.get('cursor_offset_x', 0)} y={cap.get('cursor_offset_y', 0)})"
        )

    window_title = profile.get("window_title_match") or "(not specified)"

    pack_filename = pack_file.name

    body = f"""# {title} — {src} → {tgt}

{HEADER_MARKER}

- **Game**: {title}
- **Source**: {lang_name(src)} (`{src}`)
- **Target**: {lang_name(tgt)} (`{tgt}`)
- **Glossary entries**: {len(gloss)}
- **Contributor**: {contributor}
- **Pack format**: v{fv}

## Glossary by category

| Category | Entries |
|----------|---------|
{cat_rows}
## Capture & context

- **Capture mode**: {cap_summary}
- **Window title match**: `{window_title}`
- **Game process**: `{game.get('process_name', '')}`
- **World description**: {world}
- **Style hint**: {style}
"""

    if prompt_hint:
        body += f"\n**Contributor notes** (from `profile.context.prompt_hint`):\n\n> {prompt_hint}\n"

    body += f"""
## Install

1. Download [`{pack_filename}`]({pack_filename}).
2. In Playto, open the **Profile** tab → **Import pack** → select the file.
3. Playto shows a preview dialog — choose **Import All** to copy capture settings + glossary, or **Glossary only** to keep your own capture setup.

## Contributing improvements

Open a PR against this folder following the top-level [CONTRIBUTING.md](../../../CONTRIBUTING.md). You don't need to edit this README — it is regenerated from the pack metadata on every push to main.
"""
    return body


def render_game_readme(game_dir: Path, pair_entries: list[dict]) -> str:
    # pair_entries: [{pair, pack_file, pack}]
    first_pack = pair_entries[0]["pack"]
    game = first_pack.get("game", {})
    title = game.get("title") or game_dir.name.replace("-", " ").title()
    process = game.get("process_name", "")

    rows = ""
    for pe in sorted(pair_entries, key=lambda x: x["pair"]):
        p = pe["pack"]
        src = pe["pair"].split("-")[0]
        tgt = pe["pair"].split("-")[1] if "-" in pe["pair"] else ""
        gloss = glossary_dict(p)
        contributor = p.get("contributor") or p.get("summary", {}).get("contributor") or "anonymous"
        rows += (
            f"| [`{pe['pair']}/`]({pe['pair']}/) | "
            f"{lang_name(src)} → {lang_name(tgt)} | "
            f"{contributor} | "
            f"{len(gloss)} |\n"
        )

    body = f"""# {title}

{HEADER_MARKER}

Community game pack registry for {title}. Each available (source, target) language pair lives in its own folder below.

- **Process name**: `{process}`
- **Available pairs**: {len(pair_entries)}

## Available packs

| Pair folder | Language pair | Contributor | Entries |
|-------------|---------------|-------------|---------|
{rows}
## Contributing

See the top-level [CONTRIBUTING.md](../../CONTRIBUTING.md) for the PR flow. Drop your exported `.playto-pack` into a `<source>-<target>/` folder here — no README required, both the game-level and pair-level READMEs are regenerated automatically on push to main.
"""
    return body


def collect_packs():
    """Yield (game_dir, pair_dir, pack_file, pack_json)."""
    if not PACKS_DIR.is_dir():
        return
    for game_dir in sorted(p for p in PACKS_DIR.iterdir() if p.is_dir()):
        for pair_dir in sorted(p for p in game_dir.iterdir() if p.is_dir()):
            packs = sorted(pair_dir.glob("*.playto-pack"))
            if not packs:
                continue
            pack_file = packs[0]
            try:
                pack = load_pack(pack_file)
            except json.JSONDecodeError as e:
                print(f"::warning::Skipping {pack_file.relative_to(ROOT)}: invalid JSON — {e}")
                continue
            yield game_dir, pair_dir, pack_file, pack


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if any README would change")
    args = parser.parse_args()

    to_write: list[tuple[Path, str]] = []
    game_pair_map: dict[Path, list[dict]] = {}

    for game_dir, pair_dir, pack_file, pack in collect_packs():
        pair_readme = render_pair_readme(pack_file, pack, game_dir.name, pair_dir.name)
        to_write.append((pair_dir / "README.md", pair_readme))
        game_pair_map.setdefault(game_dir, []).append(
            {"pair": pair_dir.name, "pack_file": pack_file, "pack": pack}
        )

    for game_dir, entries in game_pair_map.items():
        game_readme = render_game_readme(game_dir, entries)
        to_write.append((game_dir / "README.md", game_readme))

    changed = 0
    for path, new_content in to_write:
        existing = path.read_text(encoding="utf-8") if path.is_file() else None
        if existing != new_content:
            if args.check:
                print(f"::error::{path.relative_to(ROOT)} is out of date. Regenerate with `python scripts/generate-readmes.py`.")
            else:
                path.write_text(new_content, encoding="utf-8")
                print(f"Wrote {path.relative_to(ROOT)}")
            changed += 1

    if args.check and changed:
        print(f"\n{changed} README(s) would change. Run scripts/generate-readmes.py.")
        return 1

    if not changed:
        print("All READMEs up to date.")
    else:
        print(f"\nWrote {changed} README(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
